### ISSUE TITLE
Default options error

### ISSUE THREAD

**Issue by chimmelb** [jjongsma/grunt-eb-deploy#1]
I made a gruntfile like this:

```
var grunt = require( 'grunt' )

grunt.initConfig( {
  ebDeploy: {
    options: {
      application: 'eb-test-app',
      environment: 'eb-test-app-dev'
    },
    files: [ {
        src: [ '.ebextensions/*' ]
      }, {
        cwd: 'dist/',
        src: [ '**' ],
        expand: true
      } ]
  }
} );


grunt.loadNpmTasks( 'grunt-eb-deploy' );
```

Obviously it shouldn't have worked for me, but when I run the command `grunt -v ebDeploy` I get this error:

```
Running tasks: ebDeploy

Running "ebDeploy" task

Running "ebDeploy:files" (ebDeploy) task
Verifying property ebDeploy.files exists in config...OK
Warning: Object #<Object> has no method 'indexOf' Used --force, continuing.

Done, but with warnings.
```

Any ideas? I started the initConfig object with my own beanstalk settings, but didn't get past this error.

**Comment by chimmelb** [comment]
Adding a different environment helped. I put my `files` object into a property `only`, and then called `grunt ebDeploy:only` and got much further!

**Comment by jjongsma** [comment]
Looks like my config example is bad, I'll check.
